---
title: "LDA Effect Size (LEfSe)"
date: "Created: 2021-10-10 Modified: `r Sys.Date()`"
author: 
  - name: "Hua Zou"
    email: "zouhua1@outlook.com"
output: 
  html_notebook:
    codes: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
library(dplyr)
library(tibble)
library(data.table)
library(SummarizedExperiment)
library(lefser)
library(ggplot2)


# rm(list = ls())
options(stringsAsFactors = F)
options(future.globals.maxSize = 1000 * 1024^2)

grp <- c("control", "adenoma", "CRC")
subgrp <- c("HC", "AA", "CRC")
grp.col <- c("#568875", "#73FAFC", "#EE853D")
```


### Importing Data
```{r}
ExprSet <- readRDS("../../Result/Profile/species_profile.RDS")
table(pData(ExprSet)$SubGroup)
```


### Function
```{r}
# building SummarizedExperiment data
get_Experiment_Set <- function(dataset=ExprSet,
                               group_info="SubGroup",
                               group_name=subgrp[c(3,1)],
                               occurrence=0.2){
  
  # dataset=ExprSet
  # group_info="SubGroup"
  # group_name=subgrp[c(3, 1)]
  # occurrence=0.2
  
  phenotype <- pData(dataset)
  profile <- exprs(dataset)
  colnames(phenotype)[which(colnames(phenotype) == group_info)] <- "Group"
  
  if(length(group_name) == 3){
    group_name2 <- c("CRC", "non_CRC")
    pheno <- phenotype %>%
      rownames_to_column("SampleID") %>%
      filter(Group%in%group_name) %>%
      mutate(Group=ifelse(Group == group_name2[1], group_name2[1], group_name2[2])) %>%
      mutate(Group=factor(Group, levels = group_name2)) %>%
      column_to_rownames("SampleID")
    group_name <- group_name2
  }else{
    pheno <- phenotype %>%
      rownames_to_column("SampleID") %>%
      filter(Group%in%group_name) %>%
      mutate(Group=factor(Group, levels = group_name)) %>%
      column_to_rownames("SampleID")
  }
  edata <- profile[, rownames(pheno)] %>% data.frame() %>% 
      rownames_to_column("tmp") %>%
    filter(apply(dplyr::select(., -one_of("tmp")), 1, function(x) {
            sum(x != 0)/length(x)}) > occurrence) %>%
    column_to_rownames("tmp")
  
  mdat <- inner_join(pheno %>% rownames_to_column("SampleID") %>%
                       dplyr::select(SampleID, Group),
                     edata %>% t() %>% data.frame() %>%
                       rownames_to_column("SampleID"),
                     by = "SampleID") %>%
    column_to_rownames("SampleID") 
  
  colData <- mdat %>% dplyr::select(Group)
  counts <- t(mdat %>% dplyr::select(-Group))
  metaData <-  "Microbial Composition"
  se <- SummarizedExperiment(assays=list(counts=counts),
                             colData=colData,
                             metadata=metaData)
  
  return(se)
}

# lefse
get_lefse <- function(exprsdata=datSE,
                      group_info="Group",
                      kw.p=0.05,
                      wl.p=0.05,
                      lda.cutoff=2){
  
  # exprsdata=datSE
  # group_info="Group"
  # kw.p=0.05
  # wl.p=0.05
  # lda.cutoff=0
  
  res <- lefser(exprsdata,
                kruskal.threshold = kw.p,
                wilcox.threshold  = wl.p,
                lda.threshold     = lda.cutoff,
                groupCol = group_info,
                blockCol = NULL,
                assay    = 1L,
                trim.names = TRUE)
  
  return(res)
}

get_lefse_plot <- function(lefse=lefse_res,
                           group_name=subgrp[c(3,1)],
                           group_col=grp.col[c(3,1)]){
  
  # lefse=lefse_res
  # group_name=subgrp[c(3,1)]
  # group_col=grp.col[c(3,1)]
  
  if(length(group_name) == 3){
    group_name2 <- c("CRC", "non_CRC")
    group_name <- group_name2
  }

  plotdata <- lefse %>% mutate(Group=ifelse(scores > 0, group_name[2], group_name[1])) %>%
    mutate(Group=factor(Group, levels = group_name))

  pl <- ggplot(plotdata, aes(x=reorder(Names, scores), y=scores))+ 
          ylab("LDA SCORE (log 10)")+
          xlab("")+
          geom_bar(stat="identity", aes(fill=Group), color="black")+
          scale_fill_manual(values=group_col)+
          coord_flip()+
          theme_bw()+
          theme(axis.ticks.length = unit(0.4, "lines"), 
                axis.ticks = element_line(color="black"),
                axis.line = element_line(color="black"),
                axis.title.x = element_text(color="black", size=12, face="bold"),
                axis.text.x = element_text(color="black", size=10, face="bold"),
                axis.text.y = element_text(color="black", size=10, face="italic"),
                text = element_text(size=8, color="black", family="serif"),
                legend.title=element_blank(),
                legend.text=element_text(size=12, face="bold", color="black",
                                           margin=margin(r=20)),
                #legend.position = c(-1,-0.1),
                legend.position = c(.7, .05),
                legend.direction = "horizontal",
                legend.key.width = unit(0.8, "cm"),
                legend.key.height = unit(0.5, "cm")) 
  return(pl)
    
}
```


### CRC vs HC
```{r, fig.width=7, fig.height=8}
datSE <- get_Experiment_Set(dataset=ExprSet,
                            group_info="SubGroup",
                            group_name=subgrp[c(3,1)])
lefse_res <- get_lefse(exprsdata=datSE, 
                       group_info="Group", 
                       kw.p=0.05, 
                       wl.p=0.05, 
                       lda.cutoff=0)

if(!dir.exists("../../Result/lefse")){
  dir.create("../../Result/lefse", recursive = TRUE)
}

write.csv(lefse_res, "../../Result/lefse/CRC_HC_species_lefse_score.csv", row.names = F)

get_lefse_plot(lefse=lefse_res,
               group_name=subgrp[c(3,1)],
               group_col=grp.col[c(3,1)])
```


### CRC vs AA
```{r, fig.width=7, fig.height=8}
datSE <- get_Experiment_Set(dataset=ExprSet,
                            group_info="SubGroup",
                            group_name=subgrp[c(3,2)])
lefse_res <- get_lefse(exprsdata=datSE, 
                       group_info="Group", 
                       kw.p=0.05, 
                       wl.p=0.05, 
                       lda.cutoff=0)

if(!dir.exists("../../Result/lefse")){
  dir.create("../../Result/lefse", recursive = TRUE)
}

write.csv(lefse_res, "../../Result/lefse/CRC_AA_species_lefse_score.csv", row.names = F)

get_lefse_plot(lefse=lefse_res,
               group_name=subgrp[c(3,2)],
               group_col=grp.col[c(3,2)])
```


### CRC vs NonCRC
```{r, fig.width=7, fig.height=8}
datSE <- get_Experiment_Set(dataset=ExprSet,
                            group_info="SubGroup",
                            group_name=subgrp[c(3,2,1)])
lefse_res <- get_lefse(exprsdata=datSE, 
                       group_info="Group", 
                       kw.p=0.05, 
                       wl.p=0.05, 
                       lda.cutoff=0)

if(!dir.exists("../../Result/lefse")){
  dir.create("../../Result/lefse", recursive = TRUE)
}

write.csv(lefse_res, "../../Result/lefse/CRC_NonCRC_species_lefse_score.csv", row.names = F)

get_lefse_plot(lefse=lefse_res,
               group_name=subgrp[c(3,1)],
               group_col=grp.col[c(3,1)])
```


### systemic information
```{r}
sessionInfo()
```


### Reference

1. [lefser](https://bioconductor.org/packages/devel/bioc/html/lefser.html)