---
title: "microbiota composition: stacked barplot"
date: "Created: 2021-09-18 Modified: `r Sys.Date()`"
output: 
  html_notebook:
    codes: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
library(dplyr)
library(tibble)
library(data.table)
library(ggpubr)
library(scales)
library(varhandle)

# rm(list = ls())
options(stringsAsFactors = F)
options(future.globals.maxSize = 1000 * 1024^2)

grp <- c("control", "adenoma", "CRC")
subgrp <- c("HC", "AA", "CRC")
grp.col <- c("#568875", "#73FAFC", "#EE853D")
top.col <- c("#6C326C", "#77A2D1", "#FFD169", "#635F5F", "#D4D09A",
             "#993116", "#6798CE", "#146666", "#CE9924", "#6D659D",
             "#9F9B27", "#6D659D", "#9F9B27", "#C80b8A", "#2C3A89",
             "#C8C5C5", "#90E2BF", "#FDAB4D", "#F4F4E8", "#B054BF",
             "#FCE873", "#FFCCDB", "#AFD300", "#B089D8", "#F96E6F",
             "#AAD3ED", "#639BCE")
```


### Importing Data 
```{r}
ExprSet <- readRDS("../../Result/Profile/species_profile.RDS")
table(pData(ExprSet)$SubGroup)
```


### Function
```{r}
wilcox_fun <- function(datset=ExprSet,
                       group_info="SubGroup",
                       group_name=subgrp[c(1, 3)]){
  
  # datset=ExprSet
  # group_info="SubGroup"
  # group_name=subgrp[c(1, 3)]
  
  phenotype <- pData(datset)
  profile <- exprs(datset)
  # feature <- fData(datset)
  
  colnames(phenotype)[which(colnames(phenotype) == group_info)] <- "Group"
  if(length(group_name) == 3){
    group_name2 <- c("CRC", "non_CRC")
    pheno <- phenotype %>%
      rownames_to_column("SampleID") %>%
      filter(Group%in%group_name) %>%
      mutate(Group=ifelse(Group == group_name2[1], group_name2[1], group_name2[2])) %>%
      mutate(Group=factor(Group, levels = group_name2))
    group_name <- group_name2
  }else{
    pheno <- phenotype %>%
      rownames_to_column("SampleID") %>%
      filter(Group%in%group_name) %>%
      mutate(Group=factor(Group, levels = group_name))
  }  
  edata <- profile[, colnames(profile)%in%pheno$SampleID] %>% data.frame()
  
  # determine x with two cols and names are corret
  phen <- pheno %>% dplyr::select(SampleID, Group)
  if(length(which(colnames(phen)%in%c("SampleID","Stage"))) != 2){
    warning("x without 2 cols: DNAID, GROUP")
  }
  
  if(length(levels(phen$Group)) > 2) {
    stop("The levels of `group` are more than 2")
  }
  
  # profile
  sid <- intersect(phen$SampleID, colnames(edata))
  prf <- edata %>% dplyr::select(all_of(sid)) %>%
    rownames_to_column("tmp") %>%
    filter(apply(dplyr::select(., -one_of("tmp")), 1, 
                 function(x){sum(x > 0)/length(x)}) > 0.1) %>%
    data.frame() %>% column_to_rownames("tmp") %>%
    t() %>% data.frame()
  
  # judge no row of profile filter
  if (ncol(prf) == 0) {
    stop("No row of profile to be choosed\n")
  }
  
  # merge phenotype and profile
  mdat <- inner_join(phen %>% filter(SampleID%in%sid),
                     prf %>% rownames_to_column("SampleID"),
                     by = "SampleID")
  dat.phe <- mdat %>% dplyr::select(c(1:2))
  dat.prf <- mdat %>% dplyr::select(-2)
  pr <- levels(dat.phe$Group)
  
  res <- apply(dat.prf[, -1], 2, function(x, grp){
    dat <- as.numeric(x)
    p <- signif(wilcox.test(dat ~ grp, paired = F)$p.value, 6)
    # median
    md <- signif(median(dat), 4)
    mdn <- signif(tapply(dat, grp, median), 4)
    if ( mdn[1] > mdn[2] & p < 0.05) {
      enrich1 <- pr[1]
    } else if (mdn[1] < mdn[2] & p < 0.05) {
      enrich1 <- pr[2]
    } else if (p > 0.05 | mdn[1] == mdn[2]){
      enrich1 <- "No significance"
    }
    
    # rank
    rk <- rank(dat)
    rnk <- signif(tapply(rk, grp, mean), 4)
    if ( rnk[1] > rnk[2] & p < 0.05) {
      enrich2 <- pr[1]
    } else if (rnk[1] < rnk[2] & p < 0.05) {
      enrich2 <- pr[2]
    } else if (p > 0.05 | rnk[1] == rnk[2]){
      enrich2 <- "No significance"
    }
    occ <- signif(tapply(dat, grp, function(x){
      round(sum(x > 0)/length(x), 4)}), 4)
    
    res <- c(p,enrich1,enrich2,occ,md,mdn,rnk)
    return(res)
  }, dat.phe$Group) %>%
    t(.) %>% data.frame(.) %>%
    rownames_to_column("type") %>%
    varhandle::unfactor(.)
  
  colnames(res)[2:11] <- c("Pvalue", "Enrich_median", "Enrich_rank",
                           paste0(pr, "_occurence"), "median_all",
                           paste0(pr, "_median"), paste0(pr, "_rank"))
  res$Block <- paste0(pr[1], "_vs_", pr[2])
  number <- as.numeric(table(dat.phe$Group))
  res$Num <- paste0(pr[1], number[1], "_vs_",
                    pr[2], number[2])
  res.cln <- res %>% dplyr::select(c(1,12:13, 2:11)) %>%
    mutate(Pvalue=as.numeric(Pvalue)) %>%
    mutate(FDR=p.adjust(Pvalue, method = "BH")) %>%
    arrange(FDR, Pvalue)
  res2 <- res.cln[,c(1:4,14,5:13)]
  
  # scale profile
  dat.prf.cln <- prf[, -1]
  dat.phe.cln <- dat.phe %>% mutate(Group=ifelse(Group==pr[1], 0, 1))
  idx <- which(colnames(dat.phe.cln) == "Group")
  
  # glm result for odd ratios 95%CI
  glmFun <- function(m, n){
    dat.glm <- data.frame(group=m, marker=scale(n, center=T, scale=T))
    model <- summary(glm(group ~ marker, data = dat.glm,
                         family = binomial(link = "logit")))
    res <- signif(exp(model$coefficients["marker",1]) +
                    qnorm(c(0.025,0.5,0.975)) * model$coefficients["marker",1], 2)
    
    return(res)
  }
  
  glm_res <- t(apply(dat.prf.cln, 2, function(x, group){
    res <- glmFun(group, as.numeric(x))
    return(res)
  }, group = dat.phe.cln[, idx]))
  Odd <- glm_res %>% data.frame() %>%
    setNames(c("upper", "expected","lower")) %>%
    mutate("Odds Ratio (95% CI)" = paste0(expected, " (", lower, ";", upper, ")"))
  Odd$type <- rownames(glm_res)
  
  res_merge <- inner_join(res2,
                          Odd[, c(4:5)], by = "type")
  
  return(res_merge)
}

tax_bar_plot <- function(datset=ExprSet, 
                         testres=CRC_HC_wilcox,
                         group_info="SubGroup",
                         group_name=subgrp[c(1,3)],
                         num=20){
  # datset=ExprSet
  # testres=CRC_HC_wilcox
  # group_info="SubGroup"
  # group_name=subgrp[c(1,3)]
  # num=20
  
  phenotype <- pData(datset)
  profile <- exprs(datset)
  feature <- fData(datset)
  
  colnames(phenotype)[which(colnames(phenotype) == group_info)] <- "Group"
  if(length(group_name) == 3){
    group_name2 <- c("CRC", "non_CRC")
    pheno <- phenotype %>%
      rownames_to_column("SampleID") %>%
      filter(Group%in%group_name) %>%
      mutate(Group=ifelse(Group == group_name2[1], group_name2[1], group_name2[2])) %>%
      mutate(Group=factor(Group, levels = group_name2))
    group_name <- group_name2
  }else{
    pheno <- phenotype %>%
      rownames_to_column("SampleID") %>%
      filter(Group%in%group_name) %>%
      mutate(Group=factor(Group, levels = group_name))
  }  
  edata <- profile[, colnames(profile)%in%pheno$SampleID] %>% data.frame() %>%
    rownames_to_column("type") %>%
    filter(type%in%testres$type) %>%
    column_to_rownames("type")
  
  mdat <- inner_join(pheno %>% dplyr::select(SampleID, Group),
                     edata %>% t() %>% 
                       data.frame() %>%
                       rownames_to_column("SampleID"),
                     by = "SampleID") 
  mdat.num.mean <-  mdat %>%
    dplyr::select(-c("SampleID", "Group")) %>%
    #summarise_each(mean) %>%
    summarise(across(everything(), mean)) %>%
    tidyr::gather(key="tax", value="value") %>%
    arrange(desc(value)) %>%
    slice(c(1:num)) %>%
    mutate(tax=as.character(tax),
           tax2=tax)
  
  mdat.num.mean.no <- mdat %>%
    dplyr::select(-c("SampleID", "Group")) %>%
    #summarise_each(mean) %>%
    summarise(across(everything(), mean)) %>%
    tidyr::gather(key="tax", value="value") %>%
    arrange(desc(value)) %>%
    slice(-c(1:num)) %>%
    mutate(tax=as.character(tax))
  
  if(nrow(mdat.num.mean.no) == 0){
    other.group.mean <- data.frame()
    other.individual <- data.frame()
  }else{
    other.group.mean <- mdat %>% 
      dplyr::select(-SampleID) %>%
      group_by(Group) %>%
      #summarise_each(mean) %>%
      summarise(across(everything(), mean)) %>%
      ungroup() %>%
      tidyr::gather(key="tax", value="value", -Group) %>%
      filter(tax%in%mdat.num.mean.no$tax) %>%
      dplyr::select(-tax) %>%
      group_by(Group) %>%
      #summarise_each(sum) %>%
      summarise(across(everything(), sum)) %>%
      ungroup() %>%    
      mutate(tax="Other")
    other.individual <- mdat %>%
      dplyr::select(-Group) %>%
      tidyr::gather(key="tax", value="value", -SampleID) %>%
      filter(tax%in%mdat.num.mean.no$tax) %>%
      mutate(SampleID=factor(SampleID, levels = as.character(pheno$SampleID))) %>%
      dplyr::select(-tax) %>%
      group_by(SampleID) %>%
      #summarise_each(sum) %>%
      summarise(across(everything(), sum)) %>%
      ungroup() %>%
      mutate(tax="Other") 
  }
  
  taxonomy <- c(mdat.num.mean$tax, "Other")
  mdat.group.mean <- mdat %>%
    dplyr::select(-SampleID) %>%
    group_by(Group) %>%
    #summarise_each(mean) %>%
    summarise(across(everything(), mean)) %>%
    ungroup() %>%
    tidyr::gather(key="tax", value="value", -Group) %>%
    filter(tax%in%mdat.num.mean$tax) %>%
    mutate(Group=factor(Group, levels = group_name)) %>%
    mutate(tax=gsub("\\.", ";", tax)) %>%
    rbind(other.group.mean) %>%
    mutate(tax=factor(tax, levels = taxonomy))   
  
  mdat.individual <- mdat %>%
    dplyr::select(-Group) %>%
    tidyr::gather(key="tax", value="value", -SampleID) %>%
    filter(tax%in%mdat.num.mean$tax) %>%
    mutate(SampleID=factor(SampleID, levels = as.character(pheno$SampleID))) %>%
    mutate(tax=gsub("\\.", ";", tax)) %>%
    rbind(other.individual) %>%
    mutate(tax=factor(tax, levels = taxonomy))
  
  p_group <- ggplot(mdat.group.mean, aes(x=Group, y=value, fill=tax)) + 
    geom_bar(stat="identity", position="fill", width=0.5)+ 
    #scale_fill_brewer(palette = "Paired") +
    scale_fill_manual(values=top.col) +
    scale_y_continuous(labels=percent,
                       expand=c(0, 0)) + 
    #labs(x="", y="Relative Abundance", fill=NULL)+
    labs(x="", y="", fill=NULL)+ 
    guides(fill=guide_legend(ncol=1, bycol=TRUE, override.aes=list(size=5)))+
    theme_bw()+
    theme(axis.title.y = element_text(face="bold", color="black", size = 14),
          axis.title.x = element_text(face="bold", color="black", size = 14, vjust=-1.2),
          axis.text.y = element_text(color="black", size=10),
          axis.text.x = element_text(color="black", size=12,
                                     angle=45, vjust=0.5),
          text = element_text(size=8, color="black", family="serif"),
          panel.grid = element_blank(),
          legend.position = "right",
          legend.key.height = unit(0.6,"cm"),
          legend.text = element_text(face="italic", color="black", size=10)) 
  
  
  mdat.individual.v2 <- inner_join(pheno, mdat.individual, by="SampleID") %>%
    mutate(Group=factor(Group, levels = group_name))
  p_indi <- ggplot(mdat.individual.v2, aes(x=SampleID, y=value, fill=tax)) + 
    geom_bar(stat="identity", position="fill", width=0.5)+ 
    #scale_fill_brewer(palette = "Paired") +
    scale_fill_manual(values=top.col) +
    scale_y_continuous(labels=percent,
                       expand=c(0, 0)) +
    labs(x="", y="Relative Abundance", fill=NULL)+ 
    guides(fill=guide_legend(ncol=1, bycol=TRUE, override.aes=list(size=5)))+
    facet_wrap(facets="Group", scales="free_x")+
    theme_bw()+
    theme(axis.title.y = element_text(face="bold", color="black", size=14),
          axis.title.x = element_text(face="bold", color="black", size=10,
                                      vjust=-1.2),
          axis.text.y = element_text(color="black", size = 10),
          # axis.text.x = element_text(color="black", size = 12,
          #                            angle=45, vjust=0.5),
          axis.text.x = element_blank(),
          text = element_text(size=8, color="black", family="serif"),
          panel.grid = element_blank(),
          legend.position = "right",
          legend.key.height = unit(0.6, "cm"),
          legend.text = element_text(face="italic", color="black", size=10),
          strip.text = element_text(face="bold", size=14))  
  
  require(patchwork)
  plot_res <- (p_indi + p_group) +  
    plot_layout(ncol = 2, widths = c(3, 1), 
                guides = "collect") & theme(legend.position="right")
  return(plot_res)
}
```


### species: CRC vs HC
```{r, fig.height=5, fig.width=12}
CRC_HC_wilcox <- wilcox_fun(datset=ExprSet,
                            group_info="SubGroup",
                            group_name=subgrp[c(1, 3)])
CRC_HC_pl <- tax_bar_plot(datset=ExprSet, 
                          testres=CRC_HC_wilcox,
                          group_info="SubGroup",
                          group_name=subgrp[c(1,3)],
                          num=10)
CRC_HC_pl
```


### systemic information
```{r}
sessionInfo()
```
