---
title: "Preprocessing the TreeSummarizedExperiment Object: Pathway"
date: "Created: 2021-10-09 Updated: `r Sys.Date()`"
author: 
  - name: "Hua Zou"
    email: "zouhua1@outlook.com"
output: 
  html_notebook:
    codes: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
library(dplyr)
library(tibble)
library(ggplot2)
library(curatedMetagenomicData)
library(SummarizedExperiment)
library(TreeSummarizedExperiment)

# rm(list = ls())
options(stringsAsFactors = F)
options(future.globals.maxSize = 1000 * 1024^2)

grp <- c("control", "adenoma", "CRC")
subgrp <- c("HC", "AA", "CRC")
grp.col <- c("#568875", "#73FAFC", "#EE853D")
```


### Input data
```{r}
pathway_abundance <- readRDS("../../Study/curatedMetagenomicData/CRC_pathway_abundance_Origin.RDS")
```


### Curation
```{r}
get_ExprSet <- function(dataset=pathway_abundance,
                        occurrence=0.2){
  
  # dataset=pathway_abundance
  # occurrence=0.2
  
  assay(dataset) -> assay_data
  colData(dataset) -> col_data
  
  # filter samples
  phenotype <- data.frame(col_data) %>%
    dplyr::select(study_name, study_condition, age, gender, country, BMI) %>%
    na.omit() %>%
    filter(study_condition%in%grp) %>%
    rownames_to_column("temp") %>%
    mutate(SubGroup=ifelse(study_condition == grp[1], subgrp[1], 
                           ifelse(study_condition == grp[2], subgrp[2], subgrp[3]))) %>%
    mutate(temp=gsub("-", "_", temp)) %>%
    column_to_rownames("temp")
  
  profile <- data.frame(assay_data)
  colnames(profile) <- gsub("-", "_", colnames(assay_data))
  rownames(profile) <- gsub(" ", "_", rownames(assay_data))  
  
  feature <- data.frame(featureID=rownames(profile)) %>%
    group_by(featureID) %>%
    mutate(pathwayID=unlist(strsplit(featureID, "\\|"))[1],
           taxaID=unlist(strsplit(featureID, "\\|"))[2]) %>%
    mutate(genus=unlist(strsplit(taxaID, "\\."))[1],
           species=unlist(strsplit(taxaID, "\\."))[2])
  rownames(feature) <- rownames(profile)
  
  # pathway only 
  prof_pathway <- profile[rownames(profile)%in%subset(feature, is.na(taxaID))$featureID, ]
  prof_pathway_cln <- prof_pathway %>% dplyr::select(rownames(phenotype)) %>%
    rownames_to_column("tmp") %>%
    filter(apply(dplyr::select(., -one_of("tmp")), 1, function(x) {
            sum(x != 0)/length(x)}) > occurrence) %>%
    column_to_rownames("tmp")
  
  # pathway with taxa 
  prof_pathway_taxa <- profile[rownames(profile)%in%subset(feature, !is.na(taxaID))$featureID, ]
  # prof_pathway_taxa_cln <- prof_pathway_taxa %>% dplyr::select(rownames(phenotype)) %>%
  #   rownames_to_column("tmp") %>%
  #   filter(apply(dplyr::select(., -one_of("tmp")), 1, function(x) {
  #           sum(x != 0)/length(x)}) > occurrence) %>%
  #   column_to_rownames("tmp")
  prof_pathway_taxa_cln <- prof_pathway_taxa %>% dplyr::select(rownames(phenotype))   
  feature_taxa <- subset(feature, featureID%in%rownames(prof_pathway_taxa_cln))
  rownames(feature_taxa) <- feature_taxa$featureID

  if(!any(rownames(phenotype) == colnames(prof_pathway_cln))){
    stop("The Order of SampleID in prof_pathway is wrong")
  }
  
  if(!any(rownames(phenotype) == colnames(prof_pathway_taxa_cln))){
    stop("The Order of SampleID in prof_pathway_taxa is wrong")
  }  
  
  require(convert)
  exprs_pathway <- as.matrix(prof_pathway_cln)/100  # normalization
  exprs_pathway_taxa <- as.matrix(prof_pathway_taxa_cln)/100
  adf <- new("AnnotatedDataFrame", data=phenotype)
  fdf_taxa <- new("AnnotatedDataFrame", data=feature_taxa)
  experimentData <- new("MIAME",
          name="Hua Zou", lab="UCAS",
          contact="zouhua1@outlook.com",
          title="Tumor Experiment",
          abstract="Profile",
          url="www.zouhua.top",
          other=list(notes="microbiota"))
  expressionSet_pathway <- new(
                             "ExpressionSet",
                             exprs=exprs_pathway,
                             phenoData=adf,
                             #featureData=fdf,
                             experimentData=experimentData)
  expressionSet_pathway_taxa <- new(
                             "ExpressionSet",
                             exprs=exprs_pathway_taxa,
                             phenoData=adf,
                             featureData=fdf_taxa,
                             experimentData=experimentData)
  
  res <- list(prof_pathway=exprs_pathway, 
              prof_pathway_taxa=exprs_pathway_taxa, 
              expr_pathway=expressionSet_pathway, 
              expr_pathway_taxa=expressionSet_pathway_taxa)
  
  return(res)
}

if(!dir.exists("../../Result/Profile/")){
  dir.create("../../Result/Profile/", recursive = T)
}
```


### pathway
```{r}
pathway_abun <- get_ExprSet(dataset=pathway_abundance, occurrence=0.2)

saveRDS(pathway_abun$expr_pathway, "../../Result/Profile/pathway_ExprSet.RDS")
saveRDS(pathway_abun$expr_pathway_taxa, "../../Result/Profile/pathway_taxa_ExprSet.RDS")
write.table(pathway_abun$prof_pathway, "../../Result/Profile/pathway_profile.tsv", quote = F, row.names = T, sep = "\t")
write.table(pathway_abun$prof_pathway_taxa, "../../Result/Profile/pathway_taxa_profile.tsv", quote = F, row.names = T, sep = "\t")
```


### systemic information
```{r}
sessionInfo()
```


### Reference

1. [Introduction to TreeSummarizedExperiment](https://www.bioconductor.org/packages/release/bioc/vignettes/TreeSummarizedExperiment/inst/doc/Introduction_to_treeSummarizedExperiment.html)

2. [ExpressionSetIntroduction](http://www.bioconductor.org/packages/release/bioc/vignettes/Biobase/inst/doc/ExpressionSetIntroduction.pdf)
